# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf5cd601d96737c7291ce73fedcceb2a64175e5a0cdcd4ef7e5c37f3777df63fe497da69d81e8d34daf96740c03aca18073da20ce68d084b76bfba5702febd23

test:
  secret_key_base: 99f1cb9129db623605f607952a3cc8331287e82cdfdbefe2fb6103326ce41a97957f312c33bb20cb71b9af34c009c48f218d0c851dbd8596aaae1d8df1e272e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
